// Generated by cbindgen, DO NOT EDIT

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

extern "C" {

void hello_from_rust();

int rustacean_sum(int a, int b);

int rustacean_sum_from_ptrs(const int *a, const int *b);

} // extern "C"
