// Generated by cbindgen, DO NOT EDIT

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum SomeEnum {
  SomeEnum_A,
  SomeEnum_B,
} SomeEnum;

/**
 * Some Rustacean struct
 */
typedef struct rustacean_struct {
  int number;
  float pi;
  enum SomeEnum e;
} rustacean_struct;

/**
 * Greet from Rust
 */
void hello_from_rust(void);

/**
 * Sum two numbers
 */
int rustacean_sum(int a, int b);

/**
 * Same as [rustacean_sum] but with pointers
 */
void display_rustacean_struct(const struct rustacean_struct *s);
