// Generated by cbindgen, DO NOT EDIT

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Greet from Rust
 */
void hello_from_rust(void);

/**
 * Sum two numbers
 */
int rustacean_sum(int a, int b);

/**
 * Same as [rustacean_sum] but with pointers
 */
int rustacean_sum_from_ptrs(const int *a, const int *b);
