// Generated by cbindgen, DO NOT EDIT

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

/// Some Rustacean struct
struct rustacean_struct {
  int number;
  float pi;
};

extern "C" {

/// Greet from Rust
void hello_from_rust();

/// Sum two numbers
int rustacean_sum(int a, int b);

/// Same as [rustacean_sum] but with pointers
void display(const rustacean_struct *s);

} // extern "C"
